### ISSUE TITLE
Download Data

### ISSUE THREAD

**Issue by eggypandiangan** [ECMWFCode4Earth/fire-forecast#22]
Where I can download the data in this dir DATADIR_0p5=/ec/res4/scratch/cyjk/code4earth/0p5?

**Comment by r-maiwald** [comment]
@KaiserSF is the data somewhere publicly available?

**Comment by KaiserSF** [comment]
Hallo Robert,

Einfach Antwort: derzeit nicht.

VG!
Johannes

--
Johannes Kaiser
Climate and Environmental Research Institute NILU
https://www.nilu.no/ansatt/johannes-kaiser


From: Robert Maiwald ***@***.***>
Date: Thursday, 5 September 2024 at 14:01
To: ECMWFCode4Earth/fire-forecast ***@***.***>
Cc: Johannes Kaiser ***@***.***>, Mention ***@***.***>
Subject: Re: [ECMWFCode4Earth/fire-forecast] Download Data (Issue #22)

@KaiserSF<https://github.com/KaiserSF> is the data somewhere publicly available?

**Comment by r-maiwald** [comment]
Unfortunately the data is not publicly available. Maybe you can find some information here, if you can preprocess the data from somewhere else: https://modis.gsfc.nasa.gov/data/

Best wishes, Robert
